# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: 'Setup Dotnet Format'
description: 'Github Action for setting up dotnet tool format'
author: 'piot'
runs:
  using: 'node12'
  main: 'lib/main.js'
branding:
  color: 'green'
  icon: 'package'
